### ISSUE TITLE
Ability to run this API against any Core instance?

### ISSUE THREAD

**Issue by skokenes** [stefanwalther/qix-graphql#35]
Currently, it appears that when you use this package, it spins up its own Core instance and hooks into that to give you access to GraphQL queries for that specific instance. Is there a way to leverage that GraphQL query layer with any Core instance? That would be much more desirable to me. For example, I've got several Core containers running on my machine related to various projects. I'd love to leverage the GraphQL query layer as an independent service that I can use with any of those instances as needed.

**Comment by stefanwalther** [comment]
Thx for this feedback and thx for pointing this out.

The idea behind this solution is that you can actually connect to any existing engine, regardless whether it is:

- Qlik Core
- Qlik Sense Enterprise
- Qlik Sense Multi Cloud

Basically you just need the docker-image stefanwalther/qix-graphql (https://hub.docker.com/r/stefanwalther/qix-graphql/) and this already works right now (without considering the various security configurations).

But this needs to be clarified in the documentation, spinning up an engine for the examples is really just the demo using this, that's not a real world scenario, in real world I expect that _qix-graphql_ will be attached to an existing environment so provide a common development interface, regardless whether it is front- or backend development.

Makes sense?

**Comment by stefanwalther** [comment]
Have a look at the (radically) changed README ... does this help?

**Comment by stefanwalther** [comment]
Ping @skokenes ^

**Comment by skokenes** [comment]
Hey, thanks for updating. It is better but I still struggled at a few places:

1. Because the sample code uses the -d parameter, theres no way for me to really kill all the processes without manually removing all the containers that are created. Some sort of centralized, easy command to take down the whole thing would be nice? But maybe I'm missing the point, if its just an example GraphQL server and QIX integration, then maybe thats ok.

2. I couldn't quickly figure out how to use the Configuration variables defined to have the example point at my own Core instance. I tried 
`QIX_ENGINE_VER=12.171.0 QIX_ACCEPT_EULA=yes QIX_HOST=localhost QIX_PORT=19076  docker-compose up -d`
 with no luck

**Comment by stefanwalther** [comment]
> I couldn't quickly figure out how to use the Configuration variables defined to have the example point at my own Core instance.

Yes, that will not work, in the `docker-compose.yml` I am setting the environment variables, and not re-using it, the easiest way is probably just creating a copy of https://github.com/stefanwalther/qix-graphql/blob/master/docker-compose.yml, pointing that to your environment variables

```
version: '3.3'
services:

 qix-graphql:
    container_name: qix-graphql
    image: "stefanwalther/qix-graphql:latest@sha256:f5a4d89ff5e56a43b039ba7a127d40ba7c64101232ace266d8f50a5484f7d414"
    ports:
      - "3004:3004"
    environment:
      - QIX_HOST= localhost             ##  <== I have changed this
      - QIX_PORT= 19076                  ## <== I have changed this, too
      - HOST=localhost
      - PORT=3004
    command: ["npm", "run", "start"]
#    depends_on:
#     - qix
#      - sense-docs
```

Then do a `docker-compose up`

So to explain:

- I have removed `qix`, `sense-docs` from the original docker-compose.yml file as you already seem to have it
- The settings (`QIX_HOST` & `QIX_PORT`) are changed in the copy of `docker-compose.yml`

But probably you create a new compose file, using all your existing services + qix-graphql and combine it ... happy to help.
